### ISSUE TITLE
Migração para VueJS

### ISSUE THREAD

**Issue by teles** [seoassistant/seo-assistant-chrome-extension#15]

**Comment by dann95** [comment]
OOOOOOOPA <3, ajudas?

**Comment by teles** [comment]
Vou montar um roadmap de migração até terça que vem.
Aí possivelmente posso precisar de ajuda.
Vou usar esse repositório para aprender um pouco de VueJS.

**Comment by dann95** [comment]
@teles cria um slack pro projeto, pra poder debater, não sei qual a intenção de vocês, mas quero ajudar <3

**Comment by teles** [comment]
Criei https://seoassistant.slack.com me passa seu email para eu te adicionar?
(ps: não sei como convidar de outra forma)
